apiVersion: config.openshift.io/v1
kind: oauth
metadata:
  name: cluster
spec:
  identityProviders:
    - htpasswd:
        fileData:
          name: htpasswd-2cr76
      mappingMethod: claim
      name: htpasswd
      type: HTPasswd

