kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: etcd-backup-pvc
  namespace: openshift-etcd
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi 
  volumeMode: Filesystem
  storageClassName: azurefile-csi
